name = "jiwonz/lune_setup"
version = "0.2.4"
description = "lune setup command written in luau but for newer luau-lsp"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/lune_setup"
license = "MIT"
includes = ["bin.luau", "pesde.toml", "README.md", "LICENSE"]

[target]
environment = "lune"
bin = "bin.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
dirs = { name = "jiwonz/dirs", version = "^0.4.0" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.2" }
unzip = { name = "0x5eal/unzip", version = "^0.1.3", target = "luau" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.40.0" }
selene = { name = "pesde/selene", version = "^0.28.0" }
stylua = { name = "pesde/stylua", version = "^2.0.2" }

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.12" }
