name = "jiwonz/lune_setup"
version = "0.1.0"
description = "lune setup command written in luau but for newer luau-lsp"
authors = ["jiwonz"]
repository = "https://github.com/jiwonz/lune_setup"
license = "MIT"
includes = ["bin.luau", ".luaurc", "pesde.toml", "README.md", "LICENSE.md"]

[target]
environment = "lune"
bin = "bin.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
unzip = { repo = "0x5eal/luau-unzip", rev = "main" }
dirs = { name = "jiwonz/dirs", version = "^0.2.0" }
pathfs = { name = "jiwonz/pathfs", version = "^0.2.2" }

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.1.3" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.38.0" }
selene = { name = "pesde/selene", version = "^0.27.1" }
stylua = { name = "pesde/stylua", version = "^2.0.2" }
